
import gradio as gr
from img_captioning_app import caption_image
from auto_url import get_image_caption, get_selected_image_info

css="""
.textbox {
    font-size: 23px !important;   
    }

"""

def show_selected_image(evt: gr.SelectData):
    idx = evt.index
    selected_image = get_selected_image_info(idx)
    if selected_image:
        image, caption, classification = selected_image
        
        return (      
            gr.update(value=caption, visible=True),      
            gr.update(value=classification, visible=True)  
        )
    else:
        return (
            gr.update(visible=False),
            gr.update(visible=False)
        )

with gr.Blocks(css=css, theme=gr.themes.Soft(), title="🖼️ Web Image Captioning") as app:
    
    
    with gr.Tab("Upload Image"):
        gr.Markdown("<h2 style='text-align: center; font-size: 44px;'>🖼️ Image Captioning Application</h2>")
        gr.Markdown("<div style='text-align: center; font-size: 28px;'>Upload an image and get a caption and classification generated by the models.</div>")
        
        with gr.Row():
            with gr.Column():
                input_image = gr.Image(type="numpy", label="Upload Image")
                submit_btn_upload = gr.Button("📸 Generate Caption and Classification")
            with gr.Column():
                output_caption = gr.Label(label="🔍 Caption", elem_classes="textbox")
                output_classification = gr.Label(label="📋 Classification",elem_classes="textbox")
                
        submit_btn_upload.click(
            fn=caption_image,
            inputs=input_image,
            outputs=[output_caption, output_classification]
        )
    
    with gr.Tab("Enter URL"):
        gr.Markdown("<h2 style='text-align: center; font-size: 44px;'>🖼️ Caption Images from URL</h2>")
        gr.Markdown("<div style='text-align: center; font-size: 28px;'>Enter a URL to get AI-generated captions for images on that page.</div>")

        url_input = gr.Textbox(label="Enter URL", placeholder="https://en.wikipedia.org/")
        submit_btn_url = gr.Button("🔍 Generate Captions")

        with gr.Row():
            gallery = gr.Gallery(
                label="Image Captions",
                show_label=False,
                columns=3, 
                height=1200,
                object_fit="contain",
            )

        with gr.Column():
            selected_caption = gr.Label(label="Caption", visible=False)
            selected_classification = gr.Label(label="Classification", visible=False)

        submit_btn_url.click(
            fn=get_image_caption,
            inputs=url_input,
            outputs=gallery
        )

        gallery.select(
            fn=show_selected_image,
            inputs=None,
            outputs=[ selected_caption, selected_classification]
        )


app.launch()

